name: aliyun-boce-export

on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Remove existing file
      run: |
        if [ -f downloads/github.com-ping-result.xlsx ]; then
          rm downloads/github.com-ping-result.xlsx
        fi
        
    - name: Install dependencies
      run: npm install puppeteer

    - name: Run script to download file
      run: node download.js

    - name: Commit and push changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        ls downloads # 列出下载目录中的文件以验证文件是否存在
        #如果需要则需要修改这个github.com-ping-result.xlsx，前面的就是自己填入的域名
        git add downloads/github.com-ping-result.xlsx
        git commit -m "Add downloaded file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
